apiVersion: v1
kind: Namespace
metadata:
  name: nexus3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-nexus3-0
  namespace: nexus3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi
  storageClassName: microk8s-hostpath
